[font]
size = 12.0

[font.bold]
family = "Jetbrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
	{ key = "n", mods = "Control | Shift", action = "SpawnNewInstance" },
	{ key = "t", mods = "Control | Shift", command = { program = "thunar", args = ["."]}}
]
