[font]
size = 11.0

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
	{ key = "n", mods = "Control | Shift", action = "SpawnNewInstance" },
]
