#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
if xrandr -q | grep -q "DisplayPort-0 connected"; then
	xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rate 144
	xrandr --output eDP --off
else 
	xrandr --output eDP --primary --mode 2880x1800 --rate 90
fi

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Rice
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Keyboard layout
setxkbmap -layout se &

# Pipewire
pipewire &
pipewire-pulse &

# Polybar
polybar &

# Wallpaper
feh --bg-center ~/wallpaper/kiki-credits.png

# Window rules
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Thunar state=floating
